version: '3'

services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - scada
    ports:
      - 6379:6379
    volumes:
      - redis:/data

networks:
  scada:
    name: scada

volumes:
  redis:
    driver: local  